### ISSUE TITLE
Problem installing and starting the new pydiaid   version 0.0.30

### ISSUE THREAD

**Issue by DaliJarboui** [MannLabs/pydiaid#24]
was looking forward for the new release :) great tool. However I'm facing a big problem now. I couldn't install the latest release, the message error was about that there was a css folder exist already, so I thought because I had the last version installed, I uninstalled the old version (0.0.23), and when I tried to install the new version, I have now an error message (below). I have administrator right on the PC I'm using (W10 entr.).
appreciate the effort you are making for such great collection of tools.
Best.
 
Traceback (most recent call last):
  File "pydiaid_pyinstaller.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pydiaid\gui.py", line 15, in <module>
    from pydiaid.synchropasef.gui_synchropasef import SynchroCardWidget
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pydiaid\synchropasef\gui_synchropasef.py", line 19, in <module>
    import pydiaid.synchropasef.method_creator as method_creator
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pydiaid\synchropasef\method_creator.py", line 9, in <module>
    import pydiaid.synchropasef.method_evaluator as method_evaluator
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pydiaid\synchropasef\method_evaluator.py", line 1, in <module>
    from pydiaid.synchropasef import plots
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pydiaid\synchropasef\plots.py", line 6, in <module>
    from scipy.stats import kde
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\stats\__init__.py", line 485, in <module>
    from ._stats_py import *
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\stats\_stats_py.py", line 39, in <module>
    from scipy.spatial.distance import cdist
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\spatial\__init__.py", line 105, in <module>
    from ._kdtree import *
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\spatial\_kdtree.py", line 4, in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
  File "_ckdtree.pyx", line 10, in init scipy.spatial._ckdtree
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\sparse\__init__.py", line 283, in <module>
    from . import csgraph
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\sparse\csgraph\__init__.py", line 185, in <module>
    from ._laplacian import laplacian
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\sparse\csgraph\_laplacian.py", line 7, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\sparse\linalg\__init__.py", line 120, in <module>
    from ._isolve import *
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\sparse\linalg\_isolve\__init__.py", line 4, in <module>
    from .iterative import *
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scipy\sparse\linalg\_isolve\iterative.py", line 9, in <module>
    from . import _iterative
ImportError: DLL load failed while importing _iterative: The specified module could not be found.
Something went wrong, press any key to continue...

**Comment by URBC** [comment]
Hello, I have the same problem (win 10 Pro). Thanks

**Comment by Mach4Bruker** [comment]
Hello, I have also the same issue (Win10 pro - python 3.8).
:'-(

**Comment by josiahhutton** [comment]
Good afternoon, I've also had the same issue, and downgrading all the way to version 0.0.27 returned the same error. I fortunately had a much older version, 0.0.23, installed on another computer, and it appears to work. Downloading and installing a fresh new 0.0.23 works as well, so until this problem is resolved, 0.0.23 still works.
